# Generated by Django 5.2.5 on 2025-08-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('bus_i', models.IntegerField(primary_key=True, serialize=False, verbose_name='母线编号')),
                ('type', models.CharField(max_length=20, verbose_name='母线类型')),
                ('Pd', models.FloatField(verbose_name='总功率')),
                ('Qd', models.FloatField(verbose_name='总无功')),
                ('Gs', models.FloatField(verbose_name='总导纳')),
                ('Bs', models.FloatField(verbose_name='总 susceptance')),
                ('area', models.IntegerField(verbose_name='区域编号')),
                ('Vm', models.FloatField(verbose_name='总电压幅值')),
                ('Va', models.FloatField(verbose_name='总电压角度')),
                ('baseKV', models.FloatField(verbose_name='母线基础电压')),
                ('zone', models.IntegerField(verbose_name='区域编号')),
                ('Vmax', models.FloatField(verbose_name='总电压最大值')),
                ('Vmin', models.FloatField(verbose_name='总电压最小值')),
            ],
        ),
        migrations.CreateModel(
            name='BranchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.FloatField(verbose_name='resistance')),
                ('x', models.FloatField(verbose_name='reactance')),
                ('b', models.FloatField(verbose_name='susceptance')),
                ('rateA', models.FloatField(verbose_name='A相最大电流')),
                ('rateB', models.FloatField(verbose_name='B相最大电流')),
                ('ratio', models.FloatField(verbose_name='导纳比')),
                ('angle', models.FloatField(verbose_name='角度')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('angmin', models.FloatField(verbose_name='角度最小值')),
                ('angmax', models.FloatField(verbose_name='角度最大值')),
                ('fbus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fbus', to='配电网络.busdata')),
                ('tbus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tbus', to='配电网络.busdata')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pg', models.FloatField(verbose_name='总功率')),
                ('Qg', models.FloatField(verbose_name='总无功')),
                ('Qmax', models.FloatField(verbose_name='总无功最大值')),
                ('Qmin', models.FloatField(verbose_name='总无功最小值')),
                ('Vg', models.FloatField(verbose_name='总电压幅值')),
                ('mBase', models.FloatField(verbose_name='母线基础电压')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('Pmax', models.FloatField(verbose_name='总功率最大值')),
                ('Pmin', models.FloatField(verbose_name='总功率最小值')),
                ('Pc1', models.FloatField(verbose_name='总功率最大值')),
                ('Pc2', models.FloatField(verbose_name='总功率最大值')),
                ('Qc1min', models.FloatField(verbose_name='总无功最小值')),
                ('Qc1max', models.FloatField(verbose_name='总无功最大值')),
                ('Qc2min', models.FloatField(verbose_name='总无功最小值')),
                ('Qc2max', models.FloatField(verbose_name='总无功最大值')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='配电网络.busdata')),
            ],
        ),
    ]
