# Generated by Django 5.2.5 on 2025-08-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('配电网络', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchdata',
            options={'verbose_name': '分支数据', 'verbose_name_plural': '分支数据'},
        ),
        migrations.AlterModelOptions(
            name='busdata',
            options={'verbose_name': '母线数据', 'verbose_name_plural': '母线数据'},
        ),
        migrations.AlterModelOptions(
            name='generatordata',
            options={'verbose_name': '发电机数据', 'verbose_name_plural': '发电机数据'},
        ),
    ]
